### ISSUE TITLE
TODO Count 3/ FIXME Count 1

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-vue-wizard#16]
- [ ] TODO: specify propsData
       Commit: (9de8d94) Add core files.
       File:  [test/web/10-Wizard.js:15](https://github.com/digitalbazaar/bedrock-vue-wizard/blob/master/test/web/10-Wizard.js#L15)
       Dave Longley commented a year ago

  - [ ] TODO: consider moving to `bedrock-karma`?
       Commit: (9de8d94) Add core files.
       File:  [test/test.config.js:11](https://github.com/digitalbazaar/bedrock-vue-wizard/blob/master/test/test.config.js#L11)
       Dave Longley commented a year ago

  - [ ] FIXME: make configurable
       Commit: (9de8d94) Add core files.
       File:  [test/components/index.js:10](https://github.com/digitalbazaar/bedrock-vue-wizard/blob/master/test/components/index.js#L10)
       Dave Longley commented a year ago

  - [ ] TODO: $vm.el.something
       Commit: (9de8d94) Add core files.
       File:  [test/web/10-Wizard.js:19](https://github.com/digitalbazaar/bedrock-vue-wizard/blob/master/test/web/10-Wizard.js#L19)
       Dave Longley commented a year ago

       TODO Count          3
       FIXME Count         1
       Oldest Comment      a year ago
       Oldest Commenter    Dave Longley
       Oldest Comment      TODO: specify propsData
